[theme]

# Primary accent for interactive elements
primaryColor = '5c162e'

# Background color for the main content area
backgroundColor = '#191528'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '3c162f'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"